[package]
authors = ['Advanca Authors']
edition = '2018'
license = 'GPL-3.0'
name = 'advanca-core'
version = '0.2.0'

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'safe-mix/std',
    'frame-system/std',
    'sp-runtime/std',
    'sp-std/std',
    'sp-api/std',
]

[dependencies]
codec              = { version = "1.0.0", default-features = false, package = "parity-scale-codec" }
smart-default      = { version = "0.6.0", default-features = false }
safe-mix           = { version = "1.0.0", default-features = false }

frame-support      = { tag = "v2.0.0-rc5", git = "https://github.com/paritytech/substrate.git", default-features = false }
frame-system       = { tag = "v2.0.0-rc5", git = "https://github.com/paritytech/substrate.git", default-features = false }

sp-runtime         = { tag = "v2.0.0-rc5", git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-std             = { tag = "v2.0.0-rc5", git = "https://github.com/paritytech/substrate.git", default-features = false }
sp-api             = { tag = "v2.0.0-rc5", git = "https://github.com/paritytech/substrate.git", default-features = false }

[dev-dependencies]
sp-core            = { tag = "v2.0.0-rc5", git = "https://github.com/paritytech/substrate.git" }
sp-io              = { tag = "v2.0.0-rc5", git = "https://github.com/paritytech/substrate.git" }
sp-runtime         = { tag = "v2.0.0-rc5", git = "https://github.com/paritytech/substrate.git" }

balances           = { tag = "v2.0.0-rc5", git = "https://github.com/paritytech/substrate.git", package = "pallet-balances" }
