[package]
authors = ['Advanca Authors']
edition = '2018'
license = 'GPL-3.0'
name = 'advanca-core'
version = '0.3.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    # 'safe-mix/std',
    'frame-system/std',
    'sp-runtime/std',
    'sp-std/std',
    'sp-api/std',
]

[dev-dependencies.sp-core]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '7e9a2ae78d27cc56e053fbec3b34a1a258b89561'
version = '2.0.0-alpha.8'

[dev-dependencies.sp-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '7e9a2ae78d27cc56e053fbec3b34a1a258b89561'
version = '2.0.0-alpha.8'

[dev-dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '7e9a2ae78d27cc56e053fbec3b34a1a258b89561'
version = '2.0.0-alpha.8'

[dev-dependencies.balances]
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-balances'
rev = '7e9a2ae78d27cc56e053fbec3b34a1a258b89561'
version = '2.0.0-alpha.8'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.0'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '7e9a2ae78d27cc56e053fbec3b34a1a258b89561'
version = '2.0.0-alpha.8'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '7e9a2ae78d27cc56e053fbec3b34a1a258b89561'
version = '2.0.0-alpha.8'

# [dependencies.safe-mix]
# default-features = false
# version = '1.0.0'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '7e9a2ae78d27cc56e053fbec3b34a1a258b89561'
version = '2.0.0-alpha.8'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '7e9a2ae78d27cc56e053fbec3b34a1a258b89561'
version = '2.0.0-alpha.8'

[dependencies.sp-api]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '7e9a2ae78d27cc56e053fbec3b34a1a258b89561'
version = '2.0.0-alpha.8'

[dependencies.smart-default]
default-features = false
version = "0.6.0"
