name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: install stable toolchain and other components
        uses: actions-rs/toolchain@v1.0.5
        with:
          profile: minimal
          toolchain: stable
      - name: create cargo doc
        run: cargo doc -p advanca-core --no-deps
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc