name: Rust

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install stable toolchain and other components
      uses: actions-rs/toolchain@v1.0.5
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
    - name: install wasm
      run: ./scripts/init.sh
    - name: format check
      run: cargo fmt -- --check
    # TODO: enable the linter
    # - name: linter
    #   run: cargo clippy
