name: Rust

on: 
  pull_request:
    branches:
    - master

jobs:
  unittest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install stable toolchain and other components
      uses: actions-rs/toolchain@v1.0.5
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt, clippy
    - name: install wasm
      run: ./scripts/init.sh
    - name: run tests
      run: WASM_BUILD_TOOLCHAIN=nightly-2020-10-06 cargo test
